[package]
name = "timer"
version = "0.1.0"
authors = ["Matt Daley <m6daley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.8"
